"""update database

Revision ID: 4254ae9382b7
Revises: 5d61131344b8
Create Date: 2017-12-30 15:04:05.055664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4254ae9382b7'
down_revision = '5d61131344b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('send', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_send_user_id'), 'send', ['user_id'], unique=False)
    op.create_foreign_key(None, 'send', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'send', type_='foreignkey')
    op.drop_index(op.f('ix_send_user_id'), table_name='send')
    op.drop_column('send', 'user_id')
    # ### end Alembic commands ###
